spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/citronix
    username: citronix
    password: password
    driver-class-name: org.postgresql.Driver

  docker:
    compose:
      enabled: true
      file: src/main/docker/compose.yaml
      lifecycle-management: start_only

  jpa:
    properties:
      hibernate:
        default_schema: public

  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml
