name: citronix
services:
  postgres:
    container_name: citronix_db
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=citronix'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=citronix'
    ports:
      - '5432:5432'
    volumes:
      - citronix_db:/var/lib/postgresql/data

volumes:
    citronix_db: